/* DO NOT EDIT THIS FILE - it is machine generated - OR NOT */
#include <jni.h>
/* Header for class com_jme3_bullet_objects_PhysicsSoftBody */
#ifndef _Included_com_jme3_bullet_objects_PhysicsSoftBody
#define _Included_com_jme3_bullet_objects_PhysicsSoftBody
#ifdef __cplusplus
extern "C" {
#endif