/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_NativeSoftBodyUtil */

#ifndef _Included_com_jme3_bullet_util_NativeSoftBodyUtil
#define _Included_com_jme3_bullet_util_NativeSoftBodyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getVertices
 * Signature: (JLcom/jme3/bullet/util/DebugMeshCallback;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getVertices
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getNbFaces
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getNbFaces
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getFacesIndexes
 * Signature: (JLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getFacesIndexes
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getNbLinks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getNbLinks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getLinksIndexes
 * Signature: (JLjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getLinksIndexes
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    getNbVertices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_getNbVertices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    updateDebugMesh
 * Signature: (JLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_updateDebugMesh
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
